{% set name = "pytest-tornado" %}
{% set version = "0.5.0" %}
{% set sha256 = "214fc59d06fb81696fce3028b56dff522168ac1cfc784cfc0077b7b1e425b4cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytest
    - tornado

test:
  imports:
    - pytest_tornado

about:
  home: https://github.com/eugeniy/pytest-tornado
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: |
    A py.test plugin providing fixtures and markers to simplify testing of
    asynchronous tornado applications.

extra:
  recipe-maintainers:
    - scopatz
