# pytest-tornado is no longer maintained, so instead, we build a light fork.
{% set name = "pytest-tornado5" %}
{% set version = "2.0.0" %}
{% set sha256 = "0de5eaaff0af802a6557dd5e27ab8eab94e363c7e07a419237b9032eb8146661" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script:  "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools

test:
  imports:
    - pytest_tornado5

outputs:
  - name: {{ name|lower }}
    requirements:
      - python
      - pytest
      - tornado
  - name: pytest-tornado
    requirements:
      - {{ pin_subpackage(name, exact=True) }}

about:
  home: https://github.com/vidartf/pytest-tornado
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: |
    A py.test plugin providing fixtures and markers to simplify testing of
    asynchronous tornado applications.

extra:
  recipe-maintainers:
    - scopatz
