travis:
  secure:
    BINSTAR_TOKEN: iF3hlXQJR8TOwhGkBJi7rVCfX99yTBCpOBQZ9wEBoUQQ1YVbfVVIku6GdSK2N89sdEIaQPz+Knl1pDmJpmtrjay7p3rLG2mtrB5n6km3wAG9D2AsET18uklSYf/X3T1we8/INZWWTBbc6rYnBGVQxDeoDJ+bydEf4eUTHSKdnI5J1zuJuGZARz7hjJHSmYYunTBPF91TkzMhDDFliglw5rKflc9/5qSJBwGrS4v6a9wCy9qypfWeiS29Rfi3QbXz2M08ndvu6LQ8z2DCjxjwxBzVvwPQ4LoytICLETf9crpooaiWOOtP8Fs83YVl1HVQIRV5y1RqeDd3yLeLLANruz1/YUy+oFtmO3kKXzvZPQI6+bVi9TI+dLw7pGpmbc5bj93DtzDVcnldhHvHK/lCgsmAnLKBuyEAAwwGTPdWbqtoFXZ+C6za65yw+Q8V+JJeOTli03tXAyYbXlrd7hFtLLu3OD/NkEX5S2bMwptdBQfSdQVki/728r4YaFdPRNH88ztlcuFRYHQGVi54GY8MHrJ/vrSrBfZ09hXFmTAFegTbLzPcKhk4/adblNgwgTWh5VVC1IbmuafS+EWD6L+P5Xk8dcoc9ofXR4IziVzBRrM/ThVeh0x2z9A0BZLrOwe7i3dZrbDnRHaHeHbfczj3OdbkqlqtGypwStKnnpWhyYA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
